# Generated by Django 5.2.1 on 2025-06-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
