# Generated by Django 5.2.1 on 2025-06-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.supplier'),
        ),
    ]
