# Generated by Django 5.2.1 on 2025-06-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0003_stockhistory_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='company_location',
            new_name='supplier_location',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company_phnumber',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_phnumber',
            field=models.CharField(null=True),
        ),
    ]
