# Generated by Django 5.2.1 on 2025-06-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0004_rename_company_location_supplier_supplier_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_quatity',
            new_name='item_quantity',
        ),
    ]
