# Generated by Django 5.2.1 on 2025-06-22 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0005_rename_item_quatity_item_item_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_photo',
            new_name='item_photo1',
        ),
        migrations.AddField(
            model_name='item',
            name='item_photo2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos'),
            preserve_default=False,
        ),
    ]
